ajoute step install

diff --git a/.github/workflows/buildpipeline.yaml b/.github/workflows/buildpipeline.yaml
--- a/.github/workflows/buildpipeline.yaml
+++ b/.github/workflows/buildpipeline.yaml
@@ -24,24 +24,7 @@ jobs:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - name: Checkout code
         uses: actions/checkout@v4  # Mise à jour vers la dernière version
-      - name: Install dependencies
-        run: |
-          # Met à jour la liste des paquets et installe curl
-          sudo apt-get update
-          sudo apt-get install -y curl
-
-      - name: Install SnowCLI
-        run: |
-          # Télécharge et installe SnowCLI
-          curl -sL https://github.com/snowflakedb/snowcli/releases/latest/download/snowcli_linux_amd64.tar.gz | tar xz -C /usr/local/bin --strip-components=1
-          # Vérifie si SnowCLI a bien été installé
-          if ! command -v snow &> /dev/null; then
-            echo "SnowCLI installation failed!"
-            exit 1
-          fi
-
-    
-
+   
       - name: Set up Python
         uses: actions/setup-python@v4  # Mise à jour vers la dernière version
         with:
@@ -57,7 +40,33 @@ jobs:
         run: |
           python -m pip install --upgrade pip
           pip install -r requirements.txt
+      - name: Install SnowCLI
+        run: |
+          echo "Downloading SnowCLI..."
+          curl -L -o snowcli.tar.gz https://github.com/snowflakedb/snowcli/releases/latest/download/snowcli_linux_amd64.tar.gz
 
+          # Vérifie si le fichier a été téléchargé avec succès
+          if [[ ! -f "snowcli.tar.gz" ]]; then
+              echo "Failed to download SnowCLI!"
+              exit 1
+          fi
+
+          # Vérifie que le fichier est un format gzip
+          if file snowcli.tar.gz | grep -q 'gzip compressed data'; then
+              echo "Extracting SnowCLI..."
+              tar -xzf snowcli.tar.gz -C /usr/local/bin --strip-components=1
+          else
+              echo "Downloaded file is not in gzip format!"
+              exit 1
+          fi
+
+          # Vérifie si SnowCLI a bien été installé
+          if ! command -v snow &> /dev/null; then
+              echo "SnowCLI installation failed!"
+              exit 1
+          fi
+
+          echo "SnowCLI installed successfully!"
       # Runs a set of commands using the runners shell
       - name: Configure SnowCLI
         env:
