download snowcli

diff --git a/.github/workflows/buildpipeline.yaml b/.github/workflows/buildpipeline.yaml
--- a/.github/workflows/buildpipeline.yaml
+++ b/.github/workflows/buildpipeline.yaml
@@ -30,13 +30,13 @@ jobs:
           sudo apt-get update
           sudo apt-get install -y curl
 
-      - name: Download SnowSQL
+      - name: Install SnowCLI
         run: |
-          # Télécharge le programme d'installation de SnowSQL
-          curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.3/linux_x86_64/snowsql-1.3.2-linux_x86_64.bash
-          # Vérifie si le fichier a bien été téléchargé
-          if [ ! -f snowsql-1.3.2-linux_x86_64.bash ]; then
-            echo "SnowSQL installer not found!"
+          # Télécharge et installe SnowCLI
+          curl -sL https://github.com/snowflakedb/snowcli/releases/latest/download/snowcli_linux_amd64.tar.gz | tar xz -C /usr/local/bin --strip-components=1
+          # Vérifie si SnowCLI a bien été installé
+          if ! command -v snow &> /dev/null; then
+            echo "SnowCLI installation failed!"
             exit 1
           fi
 
