modify step setup snow

diff --git a/.github/workflows/buildpipeline.yaml b/.github/workflows/buildpipeline.yaml
--- a/.github/workflows/buildpipeline.yaml
+++ b/.github/workflows/buildpipeline.yaml
@@ -40,15 +40,28 @@ jobs:
         run: |
           python -m pip install --upgrade pip
           pip install -r requirements.txt
-      - name: Configure Snowflake connection
+     - name: Set up Snowflake connection
+        env:
+          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
+          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
+          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
+          SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
+          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
+          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
+          SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
         run: |
-          snow connection add --connection-name connect-snow --account ${{ secrets.SNOWFLAKE_ACCOUNT }} \
-            --username ${{ secrets.SNOWFLAKE_USER }} \
-            --password ${{secrets.SNOWFLAKE_PASSWORD}} \
-            --role ${{ secrets.SNOWFLAKE_ROLE }} \
-            --warehouse ${{ secrets.SNOWFLAKE_WAREHOUSE }} \
-            --database ${{ secrets.SNOWFLAKE_DATABASE }} \
-            --schema ${{ secrets.SNOWFLAKE_SCHEMA }}
+          # Configurer la connexion en utilisant les variables d'environnement
+          snow connection add --connection-name connect-snow \
+            --account-name $SNOWFLAKE_ACCOUNT \
+            --username $SNOWFLAKE_USER \
+            --password $SNOWFLAKE_PASSWORD \
+            --role $SNOWFLAKE_ROLE \
+            --warehouse $SNOWFLAKE_WAREHOUSE \
+            --database $SNOWFLAKE_DATABASE \
+            --schema $SNOWFLAKE_SCHEMA || {
+              echo "Failed to add Snowflake connection"
+              exit 1
+            }
       
       - name: Run SnowCLI Commands
         env:
